### PR TITLE
Added keyfiguresfinland

### PR DESCRIPTION
**Pull request by tuopouk**
There is the python file. Data and json files are in the assets folder.

### CODE REVIEW

**Comment by AnnMarieW** [comment]
HI @tuopouk 

Thanks for the new example app - looks interesting!

Can you remove the other unrelated files and just keep the ones for the new app?

When I tried to run this locally, the figure didn't render.  Are there things that need to be added to the requirements.txt?

**Comment by tuopouk** [comment]
Hi @AnnMarieW 

Did you mean that the figure didn't render so that the background was blank white or did you get the map showing on the screen? I was able to reproduce the blank screen with plotly version 5.11.0. For some reason it seems to be working plotly version 5.3.1. I honestly have no idea why it won't render with the higher version of plotly. Do you think we could solve this? About the files, I thought only added the json and the csv in the assets folder. I'll double check.

**Comment by AnnMarieW** [comment]
Hi @tuopouk I could get it to work with Plotly < 9.0, otherwise I just get a blank white background.  
I think this is a question for @Coding-with-Adam

**Comment by Coding-with-Adam** [comment]
hi @AnnMarieW hi @tuopouk 
It worked for me and it was fast. I used the virtual environment tied to the dash-example-index, which has Plotly 5.7.0. But I also tried with Plotly 5.11 and it worked. 
Tuomas can you please remove the other non-relevant files from the PR, as Ann suggested. I can then try to pull the PR's branch and see if it works locally again.

**Comment by tuopouk** [comment]
@Coding-with-Adam I only added the three necessary files on the latest PR.  There is the keyfiguresfinland.py in the examples folder + the key_figures_regions.csv and regions.json in the ./assets folder.

**Comment by AnnMarieW** [comment]
@tuopouk If you click on the files changed tab, you will see there are 6 files included in this PR

image

**Comment by tuopouk** [comment]
@Coding-with-Adam Thanks Adam, I see now. I deleted the two .py files. Now there are four left. For some reason I cannot delete the clock mp3 file, I can only view it.

**Comment by tuopouk** [comment]
I'll make another with only required files

**Pull request closed without merging**
