### PR TITLE
V2 new app architecture

### PR DESCRIPTION
**Pull request by AnnMarieW**
- eliminate the use of exec()
- new README and CONTRIBUTING guides

### CODE REVIEW

**Comment by IcToxi** [comment]
Hi Ann, since you called it V2, can we now create new Dash instances in examples? like `app=ProxyDash()` 🙂

**Comment by AnnMarieW** [comment]
HI @IcToxi  I just stared working on this so I haven't tried it with with different app instances yet.  Please feel free to let me know how it goes if you get to that before I do. 

The main reason for the changes in this revision was to remove the `exec()` to display the interactive apps which was causing an issue with auto generated component ids.  

Some unrelated comments:
 - In this PR, I plan on adding a way for users to display the app or the code in a full screen mode as you suggested .
 -  I made the default for your cool `bad-apple` app to be "app first" followed by the code -- which makes the app display  full screen. However, when I run it, I need to reduce my browser screen size to see the app run correctly.   Do you know what css is required to make the app scale so it's displayed in it's container without requiring scroll bars?

**Comment by IcToxi** [comment]
Hi @AnnMarieW,

In fact, we don't have the necessary to think about the independent environment now. Have you considered using Blueprint? Actually the new Dash instance just redefines the routing method, and the theme is just a matter of static resource configuration, and the low-level is still the same Flask server. So I believe that Blueprint can achieve this isolation effect. Or use `DispatcherMiddleware`.  I don't know much about combining such methods with Dash, so I'm still exploring. If you know more, please try it in this version. 

I don't think it's a good idea to use the bad-apple app as your first experiment. 😁 Because its scaling will be hindered by the font settings. And I think it would be a bit too much work if you were to simply use CSS for this feature. It's better to use a component like some kind of Overlay, I'm going to find a suitable component, and will let you know when there is good news.

**Comment by IcToxi** [comment]
Hi Ann, I think `react-grid-layout` might be a good solution if we have a callback bound to the button to change the width of the element. And I was trying to wrap it, but I didn't successfully render the children.

**Pull request merged**
