### PR TITLE
Differenced time series

### PR DESCRIPTION
**Pull request by pierreolivierbonin**
Adding this PR for the differenced time series app. Despite the inclusion of previous commits in this PR, it seems only the differenced-time-series app is in the included changes ("1 file changed"). I've been wondering about whether this is still a problem and whether I should make sure to clean the commits prior to submitting a new PR, what do you think?

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Here are some guidelines for making pull requests.  It's taken from the [contributing guide from the dash-bootstsrap-components library](https://github.com/facultyai/dash-bootstrap-components/blob/main/.github/CONTRIBUTING.md)  Thanks (Tom :slightly_smiling_face: ) 

Adhering to the following process is the best way to get your work
included in the project:

1. [Fork](https://help.github.com/articles/fork-a-repo/) the project, clone your fork,
   and configure the remotes:

   ```bash
   # Clone your fork of the repo into the current directory
   git clone https://github.com/<your-username>/dash-app-gallery.git
   # Navigate to the newly cloned directory
   cd dash-app-gallery
   # Assign the original repo to a remote called "upstream"
   git remote add upstream https://github.com/AnnMarieW/dash-app-gallery.git
   ```

2. If you cloned a while ago, get the latest changes from upstream:

   ```bash
   git checkout main
   git pull upstream main
   ```

3. Create a new topic branch (off the main project development branch) to
   contain your feature, change, or fix:

   ```bash
   git checkout -b <topic-branch-name>
   ```

4. Commit your changes in logical chunks. Please adhere to these [git commit
   message guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)
   or your code is unlikely be merged into the main project. Use Git's
   [interactive rebase](https://help.github.com/articles/about-git-rebase/)
   feature to tidy up your commits before making them public.

5. Locally merge (or rebase) the upstream development branch into your topic branch:

   ```bash
   git pull [--rebase] upstream main
   ```

6. Push your topic branch up to your fork:

   ```bash
   git push origin <topic-branch-name>
   ```

7. [Open a Pull Request](https://help.github.com/articles/about-pull-requests/)
   with a clear title and description against the `main` branch.

**Comment by Coding-with-Adam** [comment]
hi @pierreolivierbonin 
Just checking in to see where we are with this app.

**Comment by pierreolivierbonin** [comment]
> hi @pierreolivierbonin Just checking in to see where we are with this app.

hey @Coding-with-Adam 
The app is functional but it needs tuning to ensure the formatting properly displays on mobile devices. I would appreciate any assistance, _i.e._ direct suggested code changes are welcome. I'm happy to welcome a co-contributor and acknowledge them on this app, for instance :)

**Comment by Coding-with-Adam** [comment]
hi @pierreolivierbonin 
I think we can put this app on the backburner for now, because we have many examples of apps with the line chart, the RadioItems, and the dropdown.

**Comment by pierreolivierbonin** [comment]
@Coding-with-Adam that's fine, I understand. I'll close the PR then. Cheers!

**Pull request closed without merging**
