### PR TITLE
add variable layout dmc app

### PR DESCRIPTION
**Pull request by milanzmitrovic**

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Hi @milanzmitrovic 
Thanks for adding this example - I like the stocks data source, and it's great to see some more `dash-mantine-components` examples too!

I think it would be nice to show off a few more `dmc` components.  For example, instead of using `html.Br` we could use the `dcm.Space` component.  We could also use `dmc.Title` instead of `html.H2`

The example can be simplified by controlling the width of the DataTable using `style_table={"overflowX": "auto"},` rather than wrapping the table in a `dmc.Container`. Also, Plotly Express figures accept data in either "wide" or "long" format, so there is no need to transform the data.  

Here's a version I've been playing with.  The main thing I'm struggling with in both versions is that on certain screen sizes, you can't change the row/column orientation with the dropdown.  I think maybe the breakpoints are interfering.  Do you know a solution?  If not, what do you think of just relying on the breakpoints rather than having a dropdown?

```python
from dash import Dash, dcc, Input, Output, dash_table, callback
import dash_mantine_components as dmc
import plotly.express as px

data = px.data.stocks()

app = Dash(__name__)

app.layout = dmc.Container(
    [
        dmc.Title("Equity prices - Line chart and Table data", align="center"),
        dmc.Space(h="xl"),
        dcc.Dropdown(
            ["Row oriented", "Column oriented"],
            value="Row oriented",
            id="variable-layout-x-layout-dropdown",
            placeholder="select columns or rows",
        ),
        dmc.Space(h="xl"),
        dcc.Dropdown(
            options=data.columns[1:],
            id="variable-layout-x-stock-dropdown",
            multi=True,
            placeholder="select stocks",
        ),
        dmc.Space(h="xl"),
        dmc.SimpleGrid(
            [
                dcc.Graph(id="variable-layout-x-line_chart"),
                dash_table.DataTable(
                    data.to_dict("records"),
                    [{"name": i, "id": i} for i in data.columns],
                    page_size=10,
                    style_table={"overflowX": "auto"},
                ),
            ],
            cols=1,
            id="variable-layout-x-simple_grid_layout",
            breakpoints=[
                {"maxWidth": "lg", "cols": 2, "spacing": "sm"},
                {"maxWidth": "sm", "cols": 1, "spacing": "sm"},
            ],
        ),
    ],
    fluid=True,
)


@callback(
    Output("variable-layout-x-line_chart", "figure"),
    Input("variable-layout-x-stock-dropdown", "value"),
)
def select_stocks(stocks):
    if stocks is None or stocks == []:
        stocks = data.columns

    fig = px.line(data, x="date", y=stocks, )
    fig.update_layout(
        margin=dict(t=50, l=25, r=25, b=25),
        yaxis_title="Price Change",
        xaxis_title="Date",
        legend_title_text='Stocks'
    )
    return fig


@callback(
    Output("variable-layout-x-simple_grid_layout", "cols"),
    Input("variable-layout-x-layout-dropdown", "value"),
)
def grid_layout(value):
    if value == "Row oriented":
        return 2
    return 1


if __name__ == "__main__":
    app.run_server(debug=True)

```

**Comment by milanzmitrovic** [comment]
> I think it would be nice to show off a few more `dmc` components. For example, instead of using `html.Br` we could use the `dmc.Space` component. We could also use `dmc.Title` instead of `html.H2`

---> Done! I put dmc.Space(), dmc.Title(), dmc.Select(), dmc.MultiSelect().


> The example can be simplified by controlling the width of the DataTable using `style_table={"overflowX": "auto"},` rather than wrapping the table in a `dmc.Container`. Also, Plotly Express figures accept data in either "wide" or "long" format, so there is no need to transform the data.

---> Thanks for this advice, I didn't know that Plotly can work with wide data. I always used to melt it into long format :) I learned sth very important in this example! Now code looks much easier to understand.


> Here's a version I've been playing with. The main thing I'm struggling with in both versions is that on certain screen sizes, you can't change the row/column orientation with the dropdown. I think maybe the breakpoints are interfering. Do you know a solution? If not, what do you think of just relying on the breakpoints rather than having a dropdown?

---> I removed following lines and layout switching (vertical, horizontal) works good!
     
```
breakpoints=[
                {"maxWidth": 980, "cols": 2, "spacing": "sm"},
                {"maxWidth": 755, "cols": 2, "spacing": "sm"},
                {"maxWidth": 600, "cols": 1, "spacing": "sm"},
    ]
```

This is new version of code, please let me know what you think. If everything is good, I will update PR :)
```


from dash import Dash, html, dcc, Input, Output, dash_table, callback
import dash_mantine_components as dmc
import plotly.express as px
import pandas as pd


data = px.data.stocks()
data['date'] = pd.to_datetime(data['date'])


app = Dash(__name__)


app.layout = dmc.Container([

    dmc.Container([
        dmc.Title('Equity prices - Line chart and Table data', style={'textAlign': 'center'}),

        dmc.Select(
            label="Layout style",
            placeholder="Select one",
            id="layout-dropdown",
            value="Row oriented",
            data=['Row oriented', 'Column oriented']
        ),

        dmc.Space(h=20),

        dmc.MultiSelect(
            label="Select stock you like!",
            placeholder="Select all stocks you like!",
            id="stock-dropdown",
            value=["GOOG", "AAPL"],
            data=[{'label': i, 'value': i} for i in data.columns[1:]]
        ),

        dmc.Text(id="multi-selected-value"),

        dmc.Space(h=20),


    ], fluid=True),

    dmc.SimpleGrid([

        dcc.Graph(id='line_chart'),

        dash_table.DataTable(
            data.to_dict('records'),
            [{"name": i, "id": i} for i in data.columns],
            page_size=10,
            style_table={'overflow-x': 'auto'}
        ),
    ],
        cols=1,
        id='simple_grid_layout'
    )
],

)


@callback(
    Output('line_chart', 'figure'),
    Input('stock-dropdown', 'value')
)
def select_stocks(stocks):

    fig = px.line(
        data_frame=data,
        x='date',
        y=stocks,
        template='simple_white'
    )

    fig.update_layout(
        margin=dict(t=50, l=25, r=25, b=25),
        yaxis_title='Price',
        xaxis_title='Date'
    )

    return fig


@callback(
    Output('simple_grid_layout', 'cols'),
    Input('layout-dropdown', 'value')
)
def grid_layout(value):
    if value == 'Row oriented':
        return 2
    else:
        return 1


if __name__ == '__main__':
    app.run_server(debug=True)

```

**Comment by AnnMarieW** [comment]
HI @milanzmitrovic 

Thanks for updating the app.   The `dmc.Select` and `dmc.MulitSelect` are nice additions, and yes, the layout updates properly using the dropdown with the breakpoints excluded.  My only concern - since we have so few dmc examples --  is that people might think dmc apps aren't responsive - and that it's necessary to use a callback to change the layout. 

I think the date in the table looks nicer if you exclude this line:
```
data['date'] = pd.to_datetime(data['date'])
```

What's the purpose of putting  half the layout in a separate ` dmc.Container`?  I think the layout is easier to understand with only one `dmc.Container`  as the  outer container of the layout. 

What is this line for?
```
dmc.Text(id="multi-selected-value"),
```

We can let Adam chime in here too :slightly_smiling_face:

**Comment by milanzmitrovic** [comment]
> HI @AnnMarieW 


> Thanks for updating the app. The `dmc.Select` and `dmc.MulitSelect` are nice additions, and yes, the layout updates properly using the dropdown with the breakpoints excluded. My only concern - since we have so few dmc examples -- is that people might think dmc apps aren't responsive - and that it's necessary to use a callback to change the layout.

--> Yeah, I see your point. That is good question. Initial idea was to create app that will show possibilities of dmc layout. I do not know, lets see what Adam thinks?


> I think the date in the table looks nicer if you exclude this line:
> 
> ```
> data['date'] = pd.to_datetime(data['date'])
> ```

--> I removed this line, seems unnecessary.

> What's the purpose of putting half the layout in a separate ` dmc.Container`? I think the layout is easier to understand with only one `dmc.Container` as the outer container of the layout.

--> It was useful in some of previous version of app, now it is unnecessary. I removed inner dmc.container.

> What is this line for?
> 
> ```
> dmc.Text(id="multi-selected-value"),
> ```

--> I do not know, probably I used it in some of previous version of app. Right now it is not used, so I removed it.

```

from dash import Dash, dcc, Input, Output, dash_table, callback
import dash_mantine_components as dmc
import plotly.express as px


data = px.data.stocks()


app = Dash(__name__)


app.layout = dmc.Container([

    dmc.Title('Equity prices - Line chart and Table data', style={'textAlign': 'center'}),

    dmc.Select(
        label="Layout style",
        placeholder="Select one",
        id="layout-dropdown",
        value="Row oriented",
        data=['Row oriented', 'Column oriented']
    ),

    dmc.Space(h=20),

    dmc.MultiSelect(
        label="Select stock you like!",
        placeholder="Select all stocks you like!",
        id="stock-dropdown",
        value=["GOOG", "AAPL"],
        data=[{'label': i, 'value': i} for i in data.columns[1:]]
    ),

    dmc.Space(h=60),

    dmc.SimpleGrid([

        dcc.Graph(id='line_chart'),

        dash_table.DataTable(
            data.to_dict('records'),
            [{"name": i, "id": i} for i in data.columns],
            page_size=10,
            style_table={'overflow-x': 'auto'}
        ),
    ],
        cols=1,
        id='simple_grid_layout'
    )
],

)


@callback(
    Output('line_chart', 'figure'),
    Input('stock-dropdown', 'value')
)
def select_stocks(stocks):

    fig = px.line(
        data_frame=data,
        x='date',
        y=stocks,
        template='simple_white'
    )

    fig.update_layout(
        margin=dict(t=50, l=25, r=25, b=25),
        yaxis_title='Price',
        xaxis_title='Date'
    )

    return fig


@callback(
    Output('simple_grid_layout', 'cols'),
    Input('layout-dropdown', 'value')
)
def grid_layout(value):
    if value == 'Row oriented':
        return 2
    else:
        return 1


if __name__ == '__main__':
    app.run_server(debug=True)


```

**Comment by Coding-with-Adam** [comment]
HI @milanzmitrovic Hi @AnnMarieW 
Thank you both for working on this app. I agree that allowing users to manipulate the app layout through a callback risks giving them the impression that dynamic layouts in DMC needs a callback and is more complicated than necessary. I much prefer the built-in breakpoints to generate dynamic layout since it's easier than the callback. 

The app has great dmc features so it's a perfect learning opportunity for our readers. Also, I added the dcc.download to the app since we have [two examples (D-12)](https://docs.google.com/spreadsheets/d/1-ezhib_RuwSDckDM2znEkIutO7MEOltQYqkc_61zUcU/edit?usp=sharing) on the example-dash-index site, and with this app we can now add a link to the dash docs download  page. 

Please feel free to comment on the code. If you're both ok with it, feel free to update the PR, Milan.

```
from dash import Dash, dcc, html, Input, Output, dash_table, callback
import dash_mantine_components as dmc
import plotly.express as px


data = px.data.stocks()


app = Dash(__name__)


app.layout = dmc.Container([

    dmc.Title('Equity prices - Line chart and Table data', style={'textAlign': 'center'}),

    dmc.Space(h=20),
    dmc.Button("Download Data", id="btn_csv"),
    dcc.Download(id="download-dataframe-csv"),
    dmc.Space(h=10),

    dmc.MultiSelect(
        label="Select stock you like!",
        placeholder="Select all stocks you like!",
        id="stock-dropdown",
        value=["GOOG", "AAPL"],
        data=[{'label': i, 'value': i} for i in data.columns[1:]]
    ),

    dmc.Space(h=60),

    dmc.SimpleGrid([

        dcc.Graph(id='line_chart'),

        dash_table.DataTable(
            data.to_dict('records'),
            [{"name": i, "id": i} for i in data.columns],
            page_size=10,
            style_table={'overflow-x': 'auto'}
        ),
    ],
        cols=2,
        id='simple_grid_layout',
        breakpoints=[
            {"maxWidth": 1500, "cols": 2, "spacing": "md"},
            {"maxWidth": 992, "cols": 2, "spacing": "sm"}, # common screen size for small laptops
            {"maxWidth": 768, "cols": 1, "spacing": "sm"}, # common screen size for tablets
        ]
    )
], fluid=True, px=100
)


@callback(
    Output('line_chart', 'figure'),
    Input('stock-dropdown', 'value')
)
def select_stocks(stocks):

    fig = px.line(
        data_frame=data,
        x='date',
        y=stocks,
        template='simple_white'
    )

    fig.update_layout(
        margin=dict(t=50, l=25, r=25, b=25),
        yaxis_title='Price',
        xaxis_title='Date'
    )

    return fig


@callback(
    Output("download-dataframe-csv", "data"),
    Input("btn_csv", "n_clicks"),
    prevent_initial_call=True,
)
def func(n_clicks):
    return dcc.send_data_frame(data.to_csv, "mydf.csv")


if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by Coding-with-Adam** [comment]
@milanzmitrovic don't forget to please update the ID so they start with `filename-x-`

**Pull request closed without merging**
