### PR TITLE
Keyfigures_finland

### PR DESCRIPTION
**Pull request by tuopouk**
I made a new pull request. I had to delete the alarm-clock sound from the assets.

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Hi @tuopouk 
Thanks for updating the PR.
Just curious - why did you make the figure with a clientside callback? 
Could you also make a version that updates the figure with a regular callback, and does not use  dcc.Store?  It would be very interesting to benchmark the performance differences.

**Comment by tuopouk** [comment]
@AnnMarieW It's really a night and day difference. I tested it with both clientside and server side and the clientside gives almost instant feedback. I put the app on render with other region layers. You can check it out. http://keyfiguresfinland.onrender.com/

**Comment by tuopouk** [comment]
the clock file is still there, I'll make a new PR

**Comment by AnnMarieW** [comment]
That's great that you saw an increase in performance.  Could you please post the server side version as well as a new file?  I'd like to try running both versions.

**Pull request closed without merging**
