### PR TITLE
Adding the app's author name in a comment at the beginning of the code

### PR DESCRIPTION
**Pull request by pierreolivierbonin**
To tag the app I have contributed and add a reference to my github. Thank you very much :)

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Hi @pierreolivierbonin 

Thank you for you contribution - that's a great example!

I'd like to make sure we are acknowledging contributors in a consistent manner.  In the image below you can  see the link to your repo in  the "Contributed by" section.

However, when you click on the GitHub contributor's link, you don't show up as a contributor to this GitHub repo, because it looks like your app was manually uploaded.    To fix this, I'll delete the current app, then accept this PR, so it shows that you added this example.  However I'd like you to remove the tag at the top of the code.  Again - this is only to be consistent with the other examples. We appreciate your contribution!


contributors

**Comment by Coding-with-Adam** [comment]
hi @AnnMarieW . Thanks for your plan to delete the app and accept the PR so @pierreolivierbonin (P-O) can get credit for it. P-O and I agreed that I would upload this app manually because he wasn't sure how to do this through git himself. But now that he feels comfortable with git and gitub and PRs, I'm glad we have a solution for him to get credit.
Thank you,

**Comment by pierreolivierbonin** [comment]
Hi @AnnMarieW and @Coding-with-Adam,

As requested, I have removed the tag at the top of the code. Thanks so much again for this opportunity to learn and contribute to this exciting project!

**Comment by AnnMarieW** [comment]
@pierreolivierbonin  This actually did not add the example in properly.   Could you please open a new PR to add this example back in?  It should be in the `examples` folder with the file name of `ecdf-app.py`

**Comment by pierreolivierbonin** [comment]
@AnnMarieW Hi, I think I did open a new PR, did it work this time?

**Pull request merged**
