### PR TITLE
country-distances app

### PR DESCRIPTION
**Pull request by tolgahancepel**

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Hey @tolgahancepel cool app!  :sunglasses: 

A couple suggestions:
- remove unused import `import pandas as pd`
- remove the lists from the callback Inputs and Outputs to make the code more compact.
- It wold be better to remove some unnecessary comments.  For example `app.layout` is pretty self documenting and doesn't need a comment.  The same goes for the variable names for the dropdowns.

```
# Application layout
app.layout = dbc.Container(
```


- On some of the country pairs the you can't see the line.  It would be helpful to add some text by the figure : "click and drag to rotate". 

- Another thing that would be helpful is to  show two figures side by side. (This is one of the most popular topics on the forum with over 75k views!)  The second figure could be this one  that zooms in and centers on the line:
```
fig = px.line_geo(dff, locations="iso_alpha", projection="orthographic", fitbounds="locations")
```

**Comment by tolgahancepel** [comment]
Hi @AnnMarieW thank you for your suggestions! I have adjusted the details, check this.

**Comment by AnnMarieW** [comment]
@tolgahancepel Looks great!  Let's just wait for Adam to take a look before merging.

**Comment by Coding-with-Adam** [comment]
Looks great. Thank you @tolgahancepel , and thank you Ann for helping improve this app.

**Pull request merged**
