### PR TITLE
Adding apps

### PR DESCRIPTION
**Pull request by pierreolivierbonin**

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Nice!  The scatter matrix app will be a great addition, but could you create a new PR for that one?  I'd like to get the ecdf app merged first.

**Comment by someshfengde** [comment]
I think @pierreolivierbonin why Adam and Ann can't get your apps merged in repo is because of branch issue 

You have to commit and push to the main branch in your forked repo and after that make a PR. 

If you need help let me know we can connect over meet

**Comment by pierreolivierbonin** [comment]
Hey @AnnMarieW, I think I finally managed to remove the scatter matrix app by doing a new commit in this branch. Please let me know if it worked. I'm still trying to figure things out, pretty new to actively contributing on Github, and I'm working on-and-off on these, so I appreciate your patience. 

I appreciate your offer @someshfengde, it's very kind of you. I will let you know for sure if I need help, thank you!

**Comment by AnnMarieW** [comment]
@pierreolivierbonin It looks like you removed the scatter matrix app correctly.  :+1: 

Could you please do another commit to update the ecdf app so it's the same as the one in the previous PR?  https://github.com/pierreolivierbonin/dash-app-gallery/blob/29cac6ae845fa0c20f2547327cbef30d1826029c/examples/ecdf-app.py

**Comment by pierreolivierbonin** [comment]
@AnnMarieW Done. Let me know if there's anything else. If I understand correctly, once this PR is closed, the next step would be to open a new PR to add the scatter matrix, as discussed?

**Comment by AnnMarieW** [comment]
Looks great!  :woman_dancing: 

And yes, the next step is to open a new PR for the scatter matrix :+1:

**Pull request merged**
