### PR TITLE
figures-with-ctx app added

### PR DESCRIPTION
**Pull request by tolgahancepel**

### CODE REVIEW

**Comment by AnnMarieW** [comment]
@tolgahancepel 

Nice use of the new `ctx.trigger_id`  feature!  I also like how you use the `align="center"` prop on the `dbc.Row` so the buttons are centered on the graph when they are side by side.

Here are some suggestions:
- remove unnecessary comments
- remove `server = app.server` since that's not necessary to run the app locally.
-  Instead of using `html.Button`, how about using `dbc.Button` so they are styled with the Bootstrap theme?  Also, in the dbc docs, there is an example of how to display a block level buttons - I think this app is a great use-case:

```
buttons = html.Div(
    [
        dbc.Button("Bar chart", id="figures-with-ctx-x-btn-bar", color="secondary"),
        dbc.Button("Line chart", id="figures-with-ctx-x-btn-line", color="secondary"),
        dbc.Button("Filled area chart", id="figures-with-ctx-x-btn-area", color="secondary"),
    ],
    className="d-grid gap-2",
)
```


image

**Comment by Coding-with-Adam** [comment]
@tolgahancepel Thank you for creating the PNG image. That is thoughtful of you. 
For future PRs, no need to create the image files anymore. Ann has developed a script that would generate these images automatically.

**Comment by tolgahancepel** [comment]
I have committed the changes, thank you. @Coding-with-Adam @AnnMarieW

**Comment by AnnMarieW** [comment]
:woman_dancing: Thanks @tolgahancepel  looks great!

**Pull request merged**
