### PR TITLE
Create extend-data.py

### PR DESCRIPTION
**Pull request by emilhe**
Add `extend-data.py` example.

### CODE REVIEW

**Review by AnnMarieW — COMMENTED** [review]
Hi @emilhe 
I :heart: this example!

To be consistent with other apps in the gallery, could you update the import statements for dash 2.0 and include a simple title, something like
```
html.H4("Display real time data in smooth animation")
```

We are also using the same `black==21.6b0` for code formatting as in the dash repo

Thanks for adding this to the gallery :slightly_smiling_face:

**Comment by Coding-with-Adam** [comment]
Thank you for the example @emilhe. I remember how this example was really the first one that made clientside callbacks clear to me when I saw it a couple of years ago :) I'm glad it's going to be part of the gallery.

Thank you for the suggestions, @AnnMarieW

**Comment by Coding-with-Adam** [comment]
Thanks @emilhe. Changes look good to me. @AnnMarieW, if you're ok with the updates, feel free to merge. I also wrote up the code for the extend-data.py file we can put in the pages folder.

```
import dash

from utils.code_and_show import example_app

dash.register_page(
    __name__,
    description="This application updates traces of a Graph component every 25ms with the clientside callback. It has a top-bottom layout and a clientside-callback.",
)

filename = __name__.split("pages.")[1]

# any notes will be displayed below the code-and-show page in a dcc.Markdown component
notes = """
#### Dash Components in App:
- [Interval](https://dash.plotly.com/dash-core-components/interval)
- [Store](https://dash.plotly.com/dash-core-components/store)
- [Clientside Callback](https://dash.plotly.com/clientside-callbacks)

##### Contributed by:
This example app was contributed by [Emil](https://github.com/emilhe)
"""

layout = example_app(filename, notes=notes)
```

**Comment by AnnMarieW** [comment]
Looks great Emil - Thanks  :woman_dancing: 

And thanks Adam I'll add the notes and the image in a separate PR

**Pull request merged**
