### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by nidhikamath2102**
Hi, I have created a pull request for the custom_spinner example. Kindly check this and let me know if any changes are needed.

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Hi @nidhikamath2102 

Thanks for this PR - but it looks like this is a duplicate of #160.

**Comment by nidhikamath2102** [comment]
I'm not sure how this happened?

In my VSCode, it shows the correct code, but the commit shows a different
code, let me do something about it. I have made some minor changes to
commit it again.

Also, I can see that PR #161 has the correct commit.
Please check commit *b13169eb4c7a502e8f7b0e96274c1380d1a9a634a* (yesterday)
and *b54597ba7014e2deaa917f033999fa3865ae33ce* (today). Hope this works
from your end too!

Please do let me know if there are any concerns

Best,
Nidhi

**Comment by AnnMarieW** [comment]
I'm not sure what's going on, but sometimes it gets confusing to have two open PRs.  Now both PRs have both app.  Let's go ahead an close this one and finish the 160 first.

**Comment by nidhikamath2102** [comment]
Works.

**Comment by nidhikamath2102** [comment]
Hi,

I have made the changes. Please check and let me know.

1) Fixed errors on the console.
2) Removed dbc component and replaced it with html.
3) Set clearable=False in the dropdown and cleaned up relevant code for
select a plot type.
4) Increased sleep time duration from 0.25 to 1 s to simulate longer
running callback.

There is no specific reason to use 2 date pickers instead of 1 single date
picker range. It just looked better to have it in the UI, hence kept it.

Let me know if this works!

Best,
Nidhi

**Pull request closed without merging**
